firstPart:
  - Mitten
  - Fuzzy
  - Kitty
  - Oscar
  - Cutie
  - Flufball
  - Snowy
  - Angel
  - Meow

connector:
  - "Mac"
  - "O'"
  - "Von "
  - ""

lastPart:
  - Mittens
  - Fluffy
  - Fuzzypaws
  - Whiskers
  - Cuteface
  - Purrpurr
  - Muffin
  - Kittyboop
  - PussyCat
